baseURL = "https://www.learnitmyway.com/"
languageCode = "en"
title = "Learn it my way"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = "UA-110144291-1"

[params]
  description = "Developer Davo's learning experiences as a self-taught software developer"
  favicon = "favicon.ico"
  author = "Developer Davo"
  twitter = "https://twitter.com/DeveloperDavo"
  github = "https://github.com/DeveloperDavo"
  disqusShortname = "learnitmyway"
