baseURL = "/"
languageCode = "en"
title = "Learn it my way"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = "UA-110144291-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Developer Davo's learning experiences as a self-taught software developer"
  author = "Developer Davo"
  about = "Thanks for visiting Learn it my way! I created this website so I could share my learning experiences as a self-taught software developer."
  twitter = "https://twitter.com/DeveloperDavo"
  github = "https://github.com/DeveloperDavo"
  disqusShortname = "learnitmyway"
