baseURL = "/"
languageCode = "en"
title = "Learn it my way"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = "UA-110144291-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "David's learning experiences as a self-taught software developer"
  author = "David"
  about = "Thanks for visiting Learn it my way! I created this website so I could share my learning experiences as a self-taught software developer."
  twitter = "https://twitter.com/learnitmyway"
  github = "https://github.com/learnitmyway"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true