baseURL = "https://www.learnitmyway.com/"
languageCode = "en"
title = "Learn it my way"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = "UA-110144291-1"

[params]
  favicon = "favicon.ico"
  author = "Developer Davo"
  background_color_class = "bg-dark-blue"
  featured_image = "/img/blackboard-background-2000w.jpeg"
  twitter = "https://twitter.com/DeveloperDavo"
  github = "https://github.com/DeveloperDavo"
