[build]
  publish = "public"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.30.2"
  HUGO_ENV = "production"
  NODE_ENV = "production"
  HUGO_BASEURL = "https://www.learnitmyway-hugo.netlify.com/"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.30.2"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.30.2"

[context.staging.environment]
  HUGO_BASEURL = "https://staging--learnitmyway-hugo.netlify.com/"
  NODE_ENV = "production"