[build]
  publish = "public"
  command = "make build"

[build.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.preview.environment]
  HUGO_BASEURL = "https://preview--learnitmyway.netlify.com/"

[context.production.environment]
  HUGO_BASEURL = "https://learnitmyway.com/"